name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-test-xpg-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v16
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build xpg-core
        run: nix-build -A xpg-core

      - name: Install xpg-core
        run: |
          nix profile install .#xpg-core
          echo "$HOME/.nix-profile/bin" >> "$GITHUB_PATH"

      - name: Build postgres core
        run: |
          cd examples/postgres
          xpg-core build

      - name: Test postgres core
        run: |
          cd examples/postgres
          xpg-core psql -v ON_ERROR_STOP=1 -c "SELECT true;"
          xpg-core -k box test
          xpg-core test

      - name: Upload to cachix
        run: |
          set -euo pipefail
          result=$(nix-build -A xpg-core)
          if [ "${GITHUB_REF}" = 'refs/heads/master' ]; then
            echo "$result" | cachix push nxpg
          fi

  build-test-xpg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: ['12', '13', '14', '15', '16', '17', '18']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v16
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build xpg
        run: nix-build -A xpg

      - name: Install xpg and GCC
        run: |
          nix profile install .#xpg nixpkgs#gcc14
          echo "$HOME/.nix-profile/bin" >> "$GITHUB_PATH"

      - name: Build postgres extension
        run: |
          cd examples/hello
          xpg -v ${{ matrix.pg-version }} build

      - name: Test postgres extension
        run: |
          cd examples/hello
          xpg -v ${{ matrix.pg-version }} psql -v ON_ERROR_STOP=1 -c "SELECT true;"
          xpg -v ${{ matrix.pg-version }} psql -v ON_ERROR_STOP=1 -c "SELECT true;"
          xpg -v ${{ matrix.pg-version }} test
          xpg -v ${{ matrix.pg-version }} pgbench -n -c 1 -T 1 -f bench/query.sql

          # test for options argument
          xpg -v ${{ matrix.pg-version }} --options "-c work_mem=8MB" psql -c "DO \$\$ BEGIN ASSERT current_setting('work_mem') = '8MB'; END \$\$;"

          # test for cassert enabled build
          xpg -v ${{ matrix.pg-version }} --cassert psql -c "DO \$\$ BEGIN ASSERT current_setting('debug_assertions') = 'on'; END \$\$;"

          # test for pg core test
          if [ "${{ matrix.pg-version }}" -ge 15 ]; then
            xpg -v ${{ matrix.pg-version }} test-core
          fi

      - if: ${{ failure() }}
        run: |
          cd examples/hello
          cat regression.out
          cat regression.diffs

      - name: Upload to cachix
        run: |
          set -euo pipefail
          result=$(nix-build -A xpg)
          if [ "${GITHUB_REF}" = 'refs/heads/master' ]; then
            echo "$result" | cachix push nxpg
          fi

  test-nix-expressions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v16
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # TODO this is failing with the nix profile way
      - name: Test xpgWithExtensions
        run: |
          nix-build tests
          cd examples/hello
          ../../result/bin/xpg -v 18 psql -v ON_ERROR_STOP=1 -c "CREATE EXTENSION plpgsql_check;"

  build-on-macos:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v16
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          set -euo pipefail
          result=$(nix-build)
          if [ "${GITHUB_REF}" = 'refs/heads/master' ]; then
            echo "$result" | cachix push nxpg
          fi

  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Enforce conventional commits
        uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: lint nix code
        run: |
          set -euo pipefail
          nix fmt -- --ci
